# PyTerrier retrieval judge: no nuggets
judge_class: "judges.pyterrier_retrieval.retrieval_judge.RetrievalJudge"

create_nuggets: false
judge: true
augment_report: false

settings:
  filebase: "pyterrier"
